# Generated by Django 2.2.6 on 2019-10-25 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_core', '0011_etag_index'),
        ('file_deletion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filetobedeleted',
            options={'verbose_name_plural': 'Files to be deleted'},
        ),
        migrations.CreateModel(
            name='DeletedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('object_storage_key', models.CharField(help_text='Object storage key of the file', max_length=1024)),
                ('filename', models.CharField(help_text='Filename', max_length=128)),
                ('etag', models.CharField(db_index=True, help_text='ETag of the file', max_length=36)),
                ('size', models.BigIntegerField(help_text='Size of the file in bytes')),
                ('sha1_unique_together', models.CharField(max_length=40)),
                ('bucket', models.ForeignKey(help_text='Details of the object storage bucket where the file is stored', on_delete=django.db.models.deletion.PROTECT, to='data_core.Bucket')),
                ('created_by', models.ForeignKey(blank=True, help_text='User by which the entry was created', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='file_deletion_deletedfile_created_by_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='User by which the entry was modified', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='file_deletion_deletedfile_modified_by_related', to=settings.AUTH_USER_MODEL)),
                ('source_file', models.ForeignKey(help_text='Name of source file from which the file was listed', on_delete=django.db.models.deletion.PROTECT, to='data_core.SourceFile')),
            ],
            options={
                'abstract': False,
                'unique_together': {('sha1_unique_together',)},
            },
        ),
    ]
