# Generated by Django 2.2.6 on 2019-10-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_deletion', '0004_maxlength_etag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedfile',
            name='filename',
            field=models.CharField(help_text='Filename', max_length=256),
        ),
    ]
