# Generated by Django 2.2.6 on 2019-10-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_deletion', '0005_maxlength_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedfile',
            name='object_storage_key',
            field=models.CharField(db_index=True, help_text='Object storage key of the file', max_length=300),
        ),
    ]
