# Generated by Django 2.2.6 on 2019-10-29 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_deletion', '0006_dbindex_osk_maxlength'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('number', models.IntegerField(help_text='Integer used to represent a batch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User by which the entry was created', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='file_deletion_batch_created_by_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='User by which the entry was modified', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='file_deletion_batch_modified_by_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='filetobedeleted',
            name='batch',
            field=models.IntegerField(help_text='Batch of file added'),
        ),
        migrations.AlterField(
            model_name='filetobedeleted',
            name='file',
            field=models.ForeignKey(help_text='File that has been added to this table', on_delete=django.db.models.deletion.PROTECT, to='data_core.File'),
        ),
        migrations.CreateModel(
            name='MarkFilesDeleteCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('command', models.CharField(help_text='Command used to add files to be deleted', max_length=500)),
                ('batch', models.ForeignKey(help_text='Batch of files to which the command relates', on_delete=django.db.models.deletion.PROTECT, to='file_deletion.Batch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User by which the entry was created', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='file_deletion_markfilesdeletecommand_created_by_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='User by which the entry was modified', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='file_deletion_markfilesdeletecommand_modified_by_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Commands marking files for deletion',
            },
        ),
    ]
