# Generated by Django 2.2.6 on 2019-10-29 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_deletion', '0007_create_batch_markfilesdeletecommand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filetobedeleted',
            old_name='batch',
            new_name='batch_old',
        ),
    ]
