# Generated by Django 2.2.6 on 2019-10-30 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_deletion', '0009_filetobedeleted_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='number',
        ),
        migrations.RemoveField(
            model_name='filetobedeleted',
            name='batch_old',
        ),
    ]
