# Generated by Django 2.2.6 on 2020-01-16 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_core', '0015_dbindex_osk_maxlength'),
        ('file_deletion', '0011_filesmarkedtonotbedeleted'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filesmarkedtonotbedeleted',
            unique_together={('batch', 'file')},
        ),
    ]
