# Generated by Django 3.0.3 on 2020-04-30 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcetype',
            name='type_general',
            field=models.ForeignKey(help_text='General type of a resource.', on_delete=django.db.models.deletion.PROTECT, to='publications.ResourceTypeGeneral'),
        ),
    ]
