# Generated by Django 3.0.3 on 2020-04-30 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_created_publisher_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='resource_type',
            field=models.ForeignKey(help_text='Description of the resource.', on_delete=django.db.models.deletion.PROTECT, to='publications.ResourceType'),
        ),
    ]
