# Generated by Django 3.0.3 on 2020-04-23 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_date_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='size',
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, help_text='Size of resource. Free text to include data volume, pages, time etc.', max_length=50, null=True)),
                ('publication', models.ForeignKey(help_text='Publication described by the size.', on_delete=django.db.models.deletion.PROTECT, to='publications.Publication')),
            ],
        ),
    ]
