# Generated by Django 3.0.3 on 2020-04-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_resource_type_foreignkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='related_identifier',
            field=models.ManyToManyField(help_text='Publication to which the identifier relates.', to='publications.RelatedIdentifier'),
        ),
        migrations.AddField(
            model_name='publication',
            name='size_bytes',
            field=models.IntegerField(default=0, help_text='Size of the resource in bytes (not a DataCite field).'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relatedidentifier',
            name='identifier',
            field=models.CharField(help_text='Uniquely identifies an item according to various schemas.', max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='relatedidentifier',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='relatedidentifier',
            name='publication',
        ),
    ]
