# Generated by Django 3.0.3 on 2020-04-30 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_related_identifier_manytomany_size_bytes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='size_bytes',
            field=models.IntegerField(help_text='Size of the resource in bytes (not a DataCite field).', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
