# Generated by Django 3.0.3 on 2020-04-23 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_size_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='format',
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(blank=True, help_text='Technical format of a resource.', max_length=100, null=True)),
                ('publication', models.ForeignKey(help_text='Publication described by a format.', on_delete=django.db.models.deletion.PROTECT, to='publications.Publication')),
            ],
        ),
    ]
