# Generated by Django 3.0.3 on 2020-04-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_format_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rights',
            options={'verbose_name_plural': 'Rights'},
        ),
        migrations.AddField(
            model_name='datetype',
            name='description',
            field=models.TextField(default='', help_text='Description of type according to DataCite Metadata Schema v4.3.', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relatedidentifiertype',
            name='description',
            field=models.TextField(default='', help_text='Description of type according to DataCite Metadata Schema v4.3.', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationtype',
            name='description',
            field=models.TextField(default='', help_text='Description of type according to DataCite Metadata Schema v4.3.', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcetypegeneral',
            name='description',
            field=models.TextField(default='', help_text='Description of type according to DataCite Metadata Schema v4.3.', max_length=1000),
            preserve_default=False,
        ),
    ]
