# Generated by Django 3.0.3 on 2020-04-30 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_size_bytes_min_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(help_text='Units of a measurement of size (not a DataCite field).', max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(default=0, help_text='Size of resource. Free text to include data volume, pages, time etc.', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='size',
            name='units',
            field=models.ForeignKey(default='', help_text='Units of measurement (not a DataCite field). Note that there is a separate field for size of the resource in bytes.', on_delete=django.db.models.deletion.PROTECT, to='publications.SizeUnits'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='size',
            unique_together={('publication', 'size', 'units')},
        ),
    ]
