# Generated by Django 3.0.3 on 2020-04-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_type_description_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetype',
            name='name',
            field=models.CharField(help_text='Type of date.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='funderidentifier',
            name='identifier',
            field=models.CharField(help_text='Unique identifier of a funding entity, according to various types.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='identifiertype',
            name='name',
            field=models.CharField(help_text='Name of an identifier type', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='nametype',
            name='name',
            field=models.CharField(help_text='Type of name', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='relatedidentifiertype',
            name='name',
            field=models.CharField(help_text='Type of related identifier', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='relationtype',
            name='name',
            field=models.CharField(help_text='Description of relationship between resource being registered and related resource.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='resourcetypegeneral',
            name='name',
            field=models.CharField(help_text='Type of a resource', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='titletype',
            name='name',
            field=models.CharField(help_text='Type of title.', max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='affiliation',
            unique_together={('name', 'identifier')},
        ),
        migrations.AlterUniqueTogether(
            name='affiliationidentifier',
            unique_together={('identifier', 'identifier_schema')},
        ),
        migrations.AlterUniqueTogether(
            name='award',
            unique_together={('number', 'uri')},
        ),
        migrations.AlterUniqueTogether(
            name='creator',
            unique_together={('publication', 'name', 'affiliation')},
        ),
        migrations.AlterUniqueTogether(
            name='creatorname',
            unique_together={('name', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='date',
            unique_together={('publication', 'date', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='format',
            unique_together={('publication', 'format')},
        ),
        migrations.AlterUniqueTogether(
            name='fundingreference',
            unique_together={('publication', 'funder_name', 'award_number')},
        ),
        migrations.AlterUniqueTogether(
            name='nameidentifier',
            unique_together={('identifier', 'identifier_schema')},
        ),
        migrations.AlterUniqueTogether(
            name='relatedidentifier',
            unique_together={('publication', 'identifier')},
        ),
        migrations.AlterUniqueTogether(
            name='resourcetype',
            unique_together={('description', 'type_general')},
        ),
        migrations.AlterUniqueTogether(
            name='rights',
            unique_together={('publication', 'identifier')},
        ),
        migrations.AlterUniqueTogether(
            name='size',
            unique_together={('publication', 'size')},
        ),
        migrations.AlterUniqueTogether(
            name='title',
            unique_together={('publication', 'name', 'type')},
        ),
    ]
