# Generated by Django 3.0.3 on 2020-04-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_size_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='format',
            field=models.ManyToManyField(blank=True, help_text='Formats of the resource.', to='publications.Format'),
        ),
        migrations.AlterField(
            model_name='format',
            name='format',
            field=models.CharField(help_text='Technical format of a resource where this is listed as a Mime type (not required by DataCite).', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='related_identifier',
            field=models.ManyToManyField(blank=True, help_text='Publication to which the identifier relates.', to='publications.RelatedIdentifier'),
        ),
        migrations.AlterUniqueTogether(
            name='format',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='format',
            name='publication',
        ),
    ]
