# Generated by Django 3.0.3 on 2020-04-23 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_unique_constraints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcetypegeneral',
            options={'verbose_name_plural': 'Resource types general'},
        ),
    ]
