# Generated by Django 3.0.3 on 2020-04-30 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_rename_format_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='rights',
            field=models.ForeignKey(blank=True, help_text='Any rights information for this resource.The property may be repeated to record complex rights characteristics.', null=True, on_delete=django.db.models.deletion.PROTECT, to='publications.Rights'),
        ),
        migrations.AlterUniqueTogether(
            name='rights',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='rights',
            name='publication',
        ),
    ]
