# Generated by Django 3.0.3 on 2020-04-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_rights_foreign_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='funding',
            field=models.ManyToManyField(blank=True, help_text='Information about funding or financial information for the resource being registered.', to='publications.FundingReference'),
        ),
        migrations.AlterUniqueTogether(
            name='fundingreference',
            unique_together={('funder_name', 'award_number')},
        ),
        migrations.RemoveField(
            model_name='fundingreference',
            name='publication',
        ),
    ]
