# Generated by Django 3.0.3 on 2020-04-29 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_title_type_non_nullable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='creator',
            unique_together={('name', 'affiliation')},
        ),
    ]
