# Generated by Django 3.0.3 on 2020-04-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_publication_creator_manytomany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='publication',
        ),
        migrations.AddField(
            model_name='creator',
            name='publication',
            field=models.ManyToManyField(help_text='Publication in which this creator has been involved or authored.', to='publications.Publication'),
        ),
    ]
