# Generated by Django 3.0.3 on 2020-04-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0012_manytomany_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='publication',
        ),
        migrations.AddField(
            model_name='publication',
            name='creator',
            field=models.ManyToManyField(help_text='Main researchers involved in the publication, or authors of the publication, in order of priority. This can be an organisation or a person.', to='publications.Creator'),
        ),
    ]
