version: '3.6'

services:
  data-workflow:
    image: data-workflow
    build:
      dockerfile: Dockerfile
      context: ./
    secrets:
      - data_workflow_mysql.conf
    volumes:
      - static_volume:/code/DataWorkflow/staticfiles
      - ./DataWorkflow:/code/DataWorkflow
      - ${DATA_WORKFLOW_DATA}:/code/DataWorkflow/data
    ports:
      - 8086:8086
    networks:
      - nginx-proxy
    links:
      - database

  reverse-proxy:
    image: nginx:1.17
    secrets:
      - data_workflow_htpasswd
    expose:
      - "1236"
    environment:
      - NGINX_PORT=1236
      - VIRTUAL_HOST=${DATA_WORKFLOW_DOMAIN}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/code/DataWorkflow/staticfiles
    links:
      - data-workflow
    networks:
      - nginx-proxy

  database:
    image: mariadb:10.4
    environment:
      - MYSQL_DATABASE=data_workflow
      - MYSQL_USER=${DATA_WORKFLOW_DB_USER}
      - MYSQL_PASSWORD=${DATA_WORKFLOW_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATA_WORKFLOW_ROOT_PASSWORD}
    volumes:
      - database:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - nginx-proxy

volumes:
  static_volume: {}
  database:

secrets:
  data_workflow_mysql.conf:
    file: ${DATA_WORKFLOW_MYSQL_CONF_PATH}
  data_workflow_htpasswd:
    file: ${DATA_WORKFLOW_HTPASSWD}

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
