# Generated by Django 2.2.6 on 2019-10-24 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_core', '0002_added_source_abstractquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucket',
            name='status',
        ),
    ]
