# Generated by Django 2.2.6 on 2019-10-24 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_core', '0006_file_model_etag_refactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketAdministration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('date_bucket_created', models.DateField(help_text='Date on which the bucket was created')),
                ('date_bucket_deleted', models.DateField(help_text='Date on which the bucket was removed')),
                ('status', models.CharField(choices=[('active', 'active'), ('deleted', 'deleted')], default='active', help_text='Status of the bucket', max_length=20)),
                ('bucket', models.ForeignKey(help_text='Bucket to which these properties relate', on_delete=django.db.models.deletion.PROTECT, to='data_core.Bucket')),
                ('created_by', models.ForeignKey(blank=True, help_text='User by which the entry was created', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_core_bucketadministration_created_by_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='User by which the entry was modified', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_core_bucketadministration_modified_by_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
