# Generated by Django 2.2.6 on 2019-10-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_core', '0008_budgetadmin_bucket_onetoone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='etag',
            field=models.CharField(help_text='ETag of the file', max_length=36),
        ),
    ]
