# Generated by Django 2.2.6 on 2019-10-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_core', '0014_maxlength_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='object_storage_key',
            field=models.CharField(db_index=True, help_text='Object storage key of the file', max_length=1024),
        ),
    ]
